### ISSUE TITLE
연사분들 개인블로그링크연결 오류

### ISSUE THREAD

**Issue by joswlv** [datayanolja/datayanolja.github.io#193]
- [카트라이더 TMI 포스트 모템-황준식님 블로그링크](https://github.com/datayanolja/datayanolja.github.io/blob/master/program.html#L282)
- [타다서비스의 데이터웨어하우스-이창현 블로그링크](https://github.com/datayanolja/datayanolja.github.io/blob/master/program.html#L364)

`a`태그에 `https://`가 빠져서 데놀주소 하위 링크로 연결됩니다.

**Comment by jy617lee** [comment]
수정되었습니다
