### ISSUE TITLE
튜토리얼과 트레이닝 세션 분리

### ISSUE THREAD

**Issue by diginori** [datayanolja/datayanolja.github.io#62]
튜토리얼과 트레이닝 세션 분리하고 시간순으로 정열하면 더 보기 좋을것 같아요.

![image](https://user-images.githubusercontent.com/2715168/31053544-a7abd36e-a6da-11e7-9591-10612782e65a.png)

**Comment by devkook** [comment]
부대일정으로 분리 

![image](https://user-images.githubusercontent.com/5794979/31474153-e13da6d2-af33-11e7-9b08-f26de7507fb0.png)
