### ISSUE TITLE
구글 웹마스터 도구 등록

### ISSUE THREAD

**Issue by corazzon** [datayanolja/datayanolja.github.io#69]
구글 검색엔진으로 "데이터야놀자"를 검색하면 공식 웹사이트가 뜨지 않습니다.
네이버 웹마스터 도구는 등록이 되어 있는데 구글에는 등록되어 있지 않은 듯 하여 건의합니다.
아래의 URL에서 구글 웹마스터 도구 등록을 할 수 있습니다.
https://www.google.com/webmasters/tools/home?hl=ko

데이터야놀자 GA사용 계정으로 등록하는 게 좋을 듯 하여 이슈로 남깁니다.

**Comment by devkook** [comment]
오 감사합니다. ^^

**Comment by devkook** [comment]
야놀자 ! 최상단 이군요 허허

![image](https://user-images.githubusercontent.com/5794979/31314099-83ed76b4-ac32-11e7-9360-a99220861b1c.png)

**Comment by corazzon** [comment]
감사합니다. 제 크롬에서는 광고가 안 뜨고 "데이터야놀자"가 가장 상단에 뜨네요 :)

![image](https://user-images.githubusercontent.com/1324021/31314109-ebaa9caa-ac32-11e7-9aab-82b96f65d803.png)

**Comment by devkook** [comment]
알려 주셔서 감사합니다. 이슈 닫을께요 ~~~
