### ISSUE TITLE
추천도서 페이지 충돌

### ISSUE THREAD

**Issue by devkook** [datayanolja/datayanolja.github.io#8]
https://datayanolja.github.io/data-book-recommendation-2017.html
에서 

메뉴가 2개이고
![image](https://user-images.githubusercontent.com/5794979/30324152-f7cd7b8e-97fa-11e7-9329-610c0ea72a4a.png)

내용도 2번 반복
![image](https://user-images.githubusercontent.com/5794979/30324172-0b95c89c-97fb-11e7-8bda-56ac358130b9.png)

**Comment by reputeio** [comment]
충돌 제거하고 커밋했습니다.
남은 부분 내용이 맞는지 확인 한 번 해주세요.

**Comment by devkook** [comment]
![image](https://user-images.githubusercontent.com/5794979/30327284-731b6214-9806-11e7-8a81-64ad707f753a.png)

감사합합니다 : )

**Comment by devkook** [comment]
앗 그런데 ... 3번째 책이 사라졌어욧 아쿠

**Comment by devkook** [comment]
![image](https://user-images.githubusercontent.com/5794979/30348119-422ff8de-9849-11e7-8154-2575267da868.png)

감사합니다 ~~~
