### ISSUE TITLE
모바일 및 태블릿 환경 메뉴이상

### ISSUE THREAD

**Issue by devkook** [datayanolja/datayanolja.github.io#9]
모바일 메뉴 안나옴 ^^
![image](https://user-images.githubusercontent.com/5794979/30369574-fa1f50f0-98af-11e7-8663-92b5251200a9.png)

태브릿 메뉴 두줄
![image](https://user-images.githubusercontent.com/5794979/30369591-08d2d6a8-98b0-11e7-87fb-185f9559ecfa.png)

모바일 언디파인 ~
![image](https://user-images.githubusercontent.com/5794979/30369606-15169710-98b0-11e7-9ec4-7b54bb5d8b5e.png)

**Comment by joswlv** [comment]
rebase로 해당 커밋은 삭제 했습니다.

**Comment by devkook** [comment]
이슈도 클로즈 셀프해주시죠 앙 ^^
